 github: [metadata]
 name: Centipede
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 #theme: jekyll-theme-leap-day
 remote_theme: pmarsceill/just-the-docs
 gfm_quirks: paragraph_end

 title: Centipede RTK
 email: contact@centipede.fr
 description: Le Real Time Kinematic collaboratif, ouvert et Open Source
 logo: "/assets/images/index/centipede_petit2.png"
 footer_content: "Copyright &copy; 2019-2020 Julien Ancelin INRAE. Distributed by an <a href=\"https://github.com/jancelin/centipede/blob/master/LICENSE\">AGPL-3.0 license.</a>"

# Enable or disable the site search
 search_enabled: true

# Set the search token separator for hyphenated-word search:
 search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
 heading_anchors: true

# Aux links for the upper right navigation
 aux_links:
   "CentipedeRTK GitHub":
     - "//github.com/jancelin/centipede"

