 github: [metadata]
 name: Centipede
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 #theme: jekyll-theme-leap-day
 remote_theme: pmarsceill/just-the-docs
 gfm_quirks: paragraph_end

 title: Centipede RTK
 email: contact@centipede.fr
 description: Le Real Time Kinematic collaboratif, ouvert et Open Source
 logo: "/assets/images/index/centipede_petit2.png"
 footer_content: '<p>Les contributeurs CentipedeRTK et l'INRAe n'assument aucune responsabilit&eacute; r&eacute;put&eacute;e avoir &eacute;t&eacute; caus&eacute;e directement ou indirectement par tout contenu de son partage des corrections RTCM3 du r&eacute;seau.</p>
<p><a href="http://creativecommons.org/licenses/by-sa/4.0/" rel="license"><img style="border-width: 0;" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" alt="Licence Creative Commons" /></a> INRAE &amp; contributeurs<br />Cette &oelig;uvre est mise &agrave; disposition selon les termes de la <a href="http://creativecommons.org/licenses/by-sa/4.0/" rel="license">Licence Creative Commons Attribution - Partage dans les M&ecirc;mes Conditions 4.0 International</a>.</p>
<p>La base de donn&eacute;es du r&eacute;seau Centipede est mise &agrave; disposition sous la licence : <a href="http://opendatacommons.org/licenses/odbl/1.0/." rel="license"> Open Database License</a></p>'
 
# Enable or disable the site search
 search_enabled: true

# Set the search token separator for hyphenated-word search:
 search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
 heading_anchors: true

# Aux links for the upper right navigation
 aux_links:
   "CentipedeRTK GitHub":
     - "https://github.com/CentipedeRTK"


theme: jekyll-theme-midnight
