 github: [metadata]
 name: Centipede
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 #theme: jekyll-theme-leap-day
 remote_theme: pmarsceill/just-the-docs
 gfm_quirks: paragraph_end

 title: Centipede RTK
 email: contact@centipede.fr
 description: Le Real Time Kinematic collaboratif, ouvert et Open Source
 url: "http://docs.centipede.fr" # the base hostname & protocol for your site, e.g. http://example.com
 logo: "/assets/images/index/centipede_petit2.png"
 footer_content: "Copyright &copy; 2019-2020 Julien Ancelin INRAE. Distributed by an <a href=\"https://github.com/jancelin/centipede/blob/master/LICENSE\">AGPL-3.0 license.</a>"
